Fixed: NameError: name 'LONG_DESCRIPTION' is not defined
Fixed NameError that occurs running setup.py due to undefined LONG_DESCRIPTION:

NameError: name 'LONG_DESCRIPTION' is not defined